version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sanic
    versions:
    - 20.12.1
    - 20.12.2
    - 21.3.1
    - 21.3.2
  - dependency-name: structlog
    versions:
    - 20.2.0
  - dependency-name: falcon
    versions:
    - 2.0.0
