version: "2"
services:

  statsdb:
    image: ajish/survey_stats-db-monet
    ports:
      - 50000

  statsserver:
    image: ajish/survey_stats
    ports:
      - "7777:7777"
    links:
      - statsdb
    command: survey_stats serve

