version: "2"
services:

  statsdb:
    image: ajish/survey_stats-db-monet
    ports:
      - 50000

  statsworker:
    image: ajish/survey_stats
    ports:
      - 7788
    links:
      - statsdb
    command: survey_stats work

  statsserver:
    image: ajish/survey_stats
    ports:
      - "7777:7777"
    links:
      - statsdb
      - statsworker
    command: survey_stats serve --stats_uri http://statsworker:7788/

