version: "3.2"
services:

  monetdb:
    image: monetdb/monetdb-r-docker
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  statsworker:
    image: ajish/survey_stats
    ports:
      - target: 7788
        published: 7788
        protocol: tcp
        mode: host
    networks:
      - backend
    depends_on:
      - monetdb
    command: survey_stats work
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: any

  statsserver:
    image: ajish/survey_stats
    ports:
      - target: 7777
        published: 7777
        protocol: tcp
        mode: host
    networks:
      - backend
    depends_on:
      - monetdb
      - statsworker
    command: survey_stats serve --statsuri http://statsworker:7788/
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: any

networks:
  backend:

volumes:
  cache:
  db-data:

