---
- hosts: statserver
  vars:
    project_repo: git://github.com/semanticbits/survey_stats
    project_location: /opt/survey_stats
    program_name: survey_stats
	conda_env: survey_env
	conda_env_file: conda_env.yml
    supervisord_configs_path: /etc/supervisor/conf.d
  roles:
    - role: andrewrothstein.conda-env
      conda_env_name: "{{ conda_root }}"
      conda_env_environment: "{{ project_location }}/{{ conda_env_file }}"
      conda_env_cleanup: True
      conda_env_activate_for_login_shell: True
      conda_env_addl_pkgs:
        - c: intel
        - c: intel/label/test
      tags:
        condaenv
    - role: supervisor
  tasks:
    - name: Clone project code.
      git:
        repo: "{{ project_repo }}"
        dest: "{{ project_location }}"
        update: yes
      tags:
        git
    - name: Create Conda environment from project environment file.
      command: "pip install -e ."
      args:
        chdir: "{{ project_location }}"
      tags:
        conda
    - name: Copy supervisord server job file to remote
      template:
        src: ./templates/run_server.j2
        dest: "{{ supervisord_configs_path }}/run_server.conf"
        owner: root
      tags:
        conf
    - name: Copy supervisord worker job file to remote
      template:
        src: ./templates/run_worker.j2
        dest: "{{ supervisord_configs_path }}/run_worker.conf"
        owner: root
      tags:
        conf
    - name: Start job
      supervisorctl:
        name: "{{ program_name }}"
        state: present
      tags:
        conf
